"""Optional local Depth Anything V2 Hypersim-Small inference; never measured depth.

No model/code downloads or ROS publication occur on import. Upstream source and
weights are explicit local inputs outside the public source archive.
"""
from pathlib import Path
import hashlib
import importlib
import subprocess
import sys
import time
import cv2
import numpy as np

UPSTREAM_COMMIT='a561b849ebae10a6f5ef49e26c83cbbcd36c71bf'
CHECKPOINT_SHA256='b782898d8a3e8be1f639de33837ed85e9b4b73e40f8f5e5cd99067588d722545'


def file_sha(path):
    h=hashlib.sha256()
    with Path(path).open('rb') as f:
        for chunk in iter(lambda:f.read(1024*1024),b''):h.update(chunk)
    return h.hexdigest()


class MetricDepthAnything:
    def __init__(self,repository,checkpoint,device='auto',input_size=518,rotation=0):
        import torch
        repository=Path(repository).resolve();checkpoint=Path(checkpoint).resolve()
        revision=subprocess.check_output(['git','-C',str(repository),'rev-parse','HEAD'],text=True).strip()
        dirty=subprocess.check_output(['git','-C',str(repository),'status','--porcelain','--untracked-files=no'],text=True)
        extra=subprocess.check_output(['git','-C',str(repository),'ls-files','--others','--exclude-standard'],text=True).splitlines()
        extra=[f for f in extra if not ('__pycache__' in Path(f).parts and Path(f).suffix=='.pyc')]
        if revision!=UPSTREAM_COMMIT or dirty.strip() or extra:raise ValueError('Expected clean pinned upstream checkout (generated bytecode allowed)')
        digest=file_sha(checkpoint)
        if digest!=CHECKPOINT_SHA256:raise ValueError('Expected official Hypersim-Small checkpoint hash')
        if input_size<56 or input_size%14:raise ValueError('Input size must be a multiple of 14, at least 56')
        source=repository/'metric_depth'
        if 'depth_anything_v2.dpt' in sys.modules:
            if Path(sys.modules['depth_anything_v2.dpt'].__file__).resolve()!=source/'depth_anything_v2/dpt.py':
                raise ValueError('Different depth_anything_v2 module already loaded')
        sys.path.insert(0,str(source))
        module=importlib.import_module('depth_anything_v2.dpt')
        if Path(module.__file__).resolve()!=source/'depth_anything_v2/dpt.py':raise ValueError('Wrong metric model module')
        self.device='cuda' if device=='auto' and torch.cuda.is_available() else 'cpu' if device=='auto' else device
        if self.device not in ('cuda','cpu'):raise ValueError('Only cpu/cuda supported')
        if rotation not in (0,90,180,270):raise ValueError('Rotation must be 0,90,180,270 clockwise')
        self.torch=torch;self.input_size=input_size;self.rotation=rotation
        self.model=module.DepthAnythingV2(encoder='vits',features=64,out_channels=[48,96,192,384],max_depth=20.)
        self.model.load_state_dict(torch.load(checkpoint,map_location='cpu',weights_only=True),strict=True)
        self.model.to(self.device).eval()
        self.metadata=dict(model='Depth-Anything-V2-Metric-Hypersim-Small',upstreamCommit=revision,checkpointSha256=digest,
                           outputUnits='model_predicted_metres',metricScaleValidated=False,maxDepth=20.,inputSize=input_size,
                           device=self.device,torch=torch.__version__,opencv=cv2.__version__,
                           deviceName=torch.cuda.get_device_name(0) if self.device=='cuda' else 'CPU',license='Apache-2.0',inputRotationClockwise=rotation,
                           outputGeometry='Prediction rotated back to the original rectified pixel coordinates')

    def predict(self,bgr):
        if bgr.dtype!=np.uint8 or bgr.ndim!=3 or bgr.shape[2]!=3:raise ValueError('uint8 BGR image required')
        t=self.torch
        if self.device=='cuda':t.cuda.synchronize()
        start=time.perf_counter()
        if self.rotation:bgr=np.ascontiguousarray(np.rot90(bgr,-self.rotation//90))
        # Upstream image2tensor chooses available hardware, so explicitly move
        # its result to the caller's selected device before executing the model.
        image,(h,w)=self.model.image2tensor(bgr,self.input_size)
        with t.inference_mode():
            prediction=self.model(image.to(self.device))
            depth=t.nn.functional.interpolate(prediction[:,None],(h,w),mode='bilinear',align_corners=True)[0,0].cpu().numpy()
        if self.device=='cuda':t.cuda.synchronize()
        elapsed=(time.perf_counter()-start)*1000
        if depth.shape!=bgr.shape[:2] or not np.isfinite(depth).all():raise ValueError('Nonfinite or misaligned model output')
        if self.rotation:depth=np.ascontiguousarray(np.rot90(depth,self.rotation//90))
        return depth.astype(np.float32),elapsed


def comparison_stats(predicted,stereo,mask):
    """Agreement with an explicitly unvalidated reference, never accuracy."""
    valid=mask&np.isfinite(predicted)&(predicted>0)&np.isfinite(stereo)&(stereo>0)
    if not valid.any():return dict(pixels=0,medianRatio=None,medianAbsoluteRelativeDisagreementPercent=None,p95AbsoluteRelativeDisagreementPercent=None)
    ratio=predicted[valid]/stereo[valid];err=np.abs(ratio-1)*100
    return dict(pixels=int(valid.sum()),medianRatio=float(np.median(ratio)),
                medianAbsoluteRelativeDisagreementPercent=float(np.median(err)),p95AbsoluteRelativeDisagreementPercent=float(np.percentile(err,95)))


def tracked_depth_change(first,second,depth_a,depth_b):
    """Observable depth change along bidirectional LK tracks, NOT jitter error.

    Actual camera/scene motion changes optical Z; no pose compensation is applied.
    """
    points=cv2.goodFeaturesToTrack(first,500,.01,8)
    if points is None:return dict(tracks=0,medianChangePercent=None,p95ChangePercent=None)
    nxt,ok,_=cv2.calcOpticalFlowPyrLK(first,second,points,None)
    if nxt is None:return dict(tracks=0,medianChangePercent=None,p95ChangePercent=None)
    back,ok_back,_=cv2.calcOpticalFlowPyrLK(second,first,nxt,None)
    if back is None:return dict(tracks=0,medianChangePercent=None,p95ChangePercent=None)
    a=points[:,0];b=nxt[:,0];h,w=first.shape
    valid=ok[:,0].astype(bool)&ok_back[:,0].astype(bool)&(np.linalg.norm(back[:,0]-a,axis=1)<=1)
    valid&=np.isfinite(b).all(1)&(b[:,0]>=0)&(b[:,0]<w-1)&(b[:,1]>=0)&(b[:,1]<h-1)
    a=np.rint(a[valid]).astype(int);b=np.rint(b[valid]).astype(int)
    da=depth_a[a[:,1],a[:,0]];db=depth_b[b[:,1],b[:,0]]
    good=np.isfinite(da)&np.isfinite(db)&(da>0)&(db>0)
    change=np.abs(db[good]/da[good]-1)*100
    return dict(tracks=int(len(change)),medianChangePercent=float(np.median(change)) if len(change) else None,
                p95ChangePercent=float(np.percentile(change,95)) if len(change) else None)
